node {
	stage('checkout') { 
		sh 'echo "temp action"' 
	}
}

stage('compiling, testing, packaging') { 
	parallel chrome: {
		runTests("Chrome")
	}, firefox: {
		runTests("Firefox")
	}, safari: {
		runTests("Safari")
	}
}

stage('archive') { 
	sh 'echo "temp action"' 
}

def runTests(browser) { 
	node {
		sh "echo running in ${browser}"
	}
}