node {
	stage('checkout') { 
		sh 'echo "temp action"' 
	}
	stage('compiling, testing, packaging') { 
		launchTests() 
	}
	stage('archive') { 
		sh 'echo "temp action"' 
	}
}

def launchTests() { 
	parallel chrome: {
		runTests("Chrome")
	}, firefox: {
		runTests("Firefox")
	}, safari: {
		runTests("Safari")
	}
}

def runTests(browser) { 
	node {
		sh "echo running in ${browser}"
		sh 'pwd'
		sh 'ls -ltrh '
	}
}